# Generated by Django 3.1.4 on 2020-12-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(default='', upload_to='contacts'),
            preserve_default=False,
        ),
    ]
